# 'brew taps'
tap "hashicorp/tap"

# 'brew install'
brew "age"
brew "amazon-ecs-cli"
brew "ansible"
brew "awscli"
brew "cloudformation-cli"
brew "colima"
brew "cookiecutter"
brew "direnv"
brew "eksctl"
brew "fluxcd/tap/flux"
brew "gitlab-runner"
brew "GnuPG"
brew "granted"
brew "hashicorp/tap/terraform"
brew "helm"
brew "htop"
brew "httpie"
# brew "k3sup"  # does not work in Actions yet
brew "k9s"
brew "neofetch"
brew "pinentry"
brew "pre-commit"
brew "SOPS"
brew "terraform"
brew "vips"
brew 'wireguard-tools'
brew "zsh-syntax-highlighting"

# 'brew cask install'
cask "1password"
cask "authy"
cask "balenaetcher"
cask "brave-browser"
cask "discord"
cask "google-chrome"
cask "iterm2"
cask "istat-menus"
cask "keepingyouawake"
cask "lens"
cask "microsoft-teams"
cask "obs"
cask "spotify"
cask "steam"
cask "visual-studio-code"
